### ISSUE TITLE
Input data is not valid yaml format: while parsing a block mapping

### ISSUE THREAD

**Issue by Legendaryaaa** [jhu-bigss/Universal_Robots_CB2_ROS2_Driver#3]
~/ros-p/src$ vcs import --input https://raw.githubusercontent.com/jhu-bigss/Universal_Robots_CB2_ROS2_Driver/main/ur_cb2_driver.repos
Input data is not valid yaml format: while parsing a block mapping
  in "<file>", line 3, column 3
expected <block end>, but found '<block mapping start>'
  in "<file>", line 20, column 4

**Comment by liushuya7** [comment]
It is fixed. Please try again. See beb78d6bfc893148012f2a0e6e6bef7e673a0b51

**Comment by Legendaryaaa** [comment]
您发送的文件已收到~
