### ISSUE TITLE
missing state interfaces: speed_scaling/speed_scaling_factor 

### ISSUE THREAD

**Issue by stytim** [jhu-bigss/Universal_Robots_CB2_ROS2_Driver#4]
I encountered the following error when running the driver on ROS2 Humble Hawksbill. Any clues how I can solve this?

`[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ur_ros2_control_node-1]: process started with pid [45282]
[INFO] [robot_state_publisher-2]: process started with pid [45284]
[INFO] [rviz2-3]: process started with pid [45286]
[INFO] [spawner-4]: process started with pid [45288]
[INFO] [spawner-5]: process started with pid [45290]
[INFO] [spawner-6]: process started with pid [45292]
[robot_state_publisher-2] [INFO] [1699021878.591164401] [robot_state_publisher]: got segment base
[robot_state_publisher-2] [INFO] [1699021878.591284884] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1699021878.591303889] [robot_state_publisher]: got segment base_link_inertia
[robot_state_publisher-2] [INFO] [1699021878.591316630] [robot_state_publisher]: got segment flange
[robot_state_publisher-2] [INFO] [1699021878.591329036] [robot_state_publisher]: got segment forearm_link
[robot_state_publisher-2] [INFO] [1699021878.591339398] [robot_state_publisher]: got segment ft_frame
[robot_state_publisher-2] [INFO] [1699021878.591347194] [robot_state_publisher]: got segment shoulder_link
[robot_state_publisher-2] [INFO] [1699021878.591357976] [robot_state_publisher]: got segment tool0
[robot_state_publisher-2] [INFO] [1699021878.591368512] [robot_state_publisher]: got segment upper_arm_link
[robot_state_publisher-2] [INFO] [1699021878.591376471] [robot_state_publisher]: got segment world
[robot_state_publisher-2] [INFO] [1699021878.591382859] [robot_state_publisher]: got segment wrist_1_link
[robot_state_publisher-2] [INFO] [1699021878.591388857] [robot_state_publisher]: got segment wrist_2_link
[robot_state_publisher-2] [INFO] [1699021878.591398616] [robot_state_publisher]: got segment wrist_3_link
[ur_ros2_control_node-1] [INFO] [1699021878.593812239] [resource_manager]: Loading hardware 'ur5' 
[ur_ros2_control_node-1] [INFO] [1699021878.613357117] [resource_manager]: Initialize hardware 'ur5' 
[ur_ros2_control_node-1] [INFO] [1699021878.613428656] [resource_manager]: Successful initialization of hardware 'ur5'
[ur_ros2_control_node-1] terminate called after throwing an instance of 'std::runtime_error'
[ur_ros2_control_node-1]   what():  Wrong state or command interface configuration.
[ur_ros2_control_node-1] missing state interfaces:
[ur_ros2_control_node-1] ' speed_scaling/speed_scaling_factor '	
[ur_ros2_control_node-1] missing command interfaces:
[ur_ros2_control_node-1] ' speed_scaling/target_speed_fraction_async_success '	
[ERROR] [ur_ros2_control_node-1]: process has died [pid 45282, exit code -6, cmd '/home/narvis/tianyu_ws/install/ur_cb2_robot_driver/lib/ur_cb2_robot_driver/ur_ros2_control_node --ros-args --params-file /tmp/launch_params_d00sfpc7 --params-file /home/narvis/tianyu_ws/install/ur_cb2_bringup/share/ur_cb2_bringup/config/ur_controllers.yaml'].`

**Comment by liushuya7** [comment]
Hi, this package hasn't been maintained for a while. I recommend using [sawUniversalRobotROS2](https://github.com/jhu-saw/sawUniversalRobotROS2) which also supports CB2 Universal Robots.
